name: rerun and track

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install notebook nbconvert pandas scikit-learn matplotlib wandb ipykernel opencv-python

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute distance_classification.ipynb --ExecutePreprocessor.timeout=-1 --ExecutePreprocessor.kernel_name=python3

      - name: Upload Notebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: distance_classification.ipynb

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update notebook after automated run" || echo "No changes to commit"
          git push || echo "No changes to push"

